### ISSUE TITLE
As a community member, I want to see old pictures so I can revisit places I know.

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#85] opened 2020-05-02 16:44 UTC
This week we realized a problem in our approach to remind the community that there's a new picture. Since we're sending emails with the homepage (bucoli.co) link:
- When old community members open old emails and click on the link, the image opened isn't the same the text was written for.
- When community members (old or new) try to open MailChimp archives, they get the same error.

Since (1) it breaks the experience of the users drastically and (2) we can't roll back and fix emails already sent; I consider this a major bug that needs to be fixed before sending the next email.

**Comment by vjpixel** [comment] 2020-05-02 17:12
Also, there are major improvements to include this.

1. We don't have an archive of the old pictures, so we don't know the pictures that were already sent. This implies many issues, for example, we need to have a look at what was already sent when choosing a new picture. Having this archive is an easy way to revisit old pictures while choosing new ones.

2. Having an archive allows us to detach the deploy of the next version of the code and the next image. We just need to change the "default" case in the switch). This decreases the probability of implementing a bug in the stable environment on the server and gives flexibility at the moment we change the picture (it doesn't need to be just before sending the email).

3. We can have the next pictures published (and hidden). This allows us to do batch work accelerating the process of choosing, approving, creating the masks, and texts. This will improve our productivity, allowing us to focus on solving creative problems (for example, the content team can focus on increasing the community and other members don't need to worry to approve the content every week).

4. This is the base for one feature that is in the Roadmap, a _system to publish photos_: https://github.com/memeLab/bucoli.co/blob/master/ROADMAP.md

**Comment by vjpixel** [comment] 2020-05-03 19:17
@tiagobugarin can you please review?

**Comment by vjpixel** [comment] 2020-05-03 19:24
@tiagobugarin you told me you have the archive of old images. can you change the code with the right file names? I left comments in the file specifying the images.

**Comment by tiagobugarin** [comment] 2020-05-03 23:08
> @tiagobugarin you told me you have the archive of old images. can you change the code with the right file names? I left comments in the file specifying the images.

just saw this one... can't do it now. but tomorrow... it is not that i have kept a ledge or something... i just have a process in mind to put every image i have in the right order... would need some time to collect everything and order correctly, including dates of release.

**Comment by tiagobugarin** [comment] 2020-05-04 01:07
done...
checkout archive function in the experiments folder
https://alpha.bucoli.co/experiencias/archive/

**Comment by tiagobugarin** [comment] 2020-05-04 01:10
> @tiagobugarin can you please review?

my revirew: the code works as intended providing a selectable function and i can say the `archive` branch is working ok.

the thing is, is it ready for merge the `master` branch, @vjpixel ?

**Comment by vjpixel** [comment] 2020-05-04 13:28
yes! I build it on the last commit on the `master` branch. @tiagobugarin

**Comment by tiagobugarin** [comment] 2020-05-04 16:39
> yes! I build it on the last commit on the `master` branch. @tiagobugarin

actually you built and merged it to the `archive` branch, @vjpixel

**Comment by vjpixel** [comment] 2020-05-04 17:14
what I tried to say is that I build on top of the last commit on the `master` branch. @tiagobugarin =)

**Comment by tiagobugarin** [comment] 2020-05-05 02:32
Following the meeting from this afternoon (may 4th, 2020) we defined some steps to resolve this issue.

First, the gathering of the historical order of the images. This task was taken by @bruquevedo who made most of it with some help from me to elucidate some technical stuff and follow some commit dates.
With this we got to a pretty fair state of the actual usage of images at the production site in the earty life of the bucoli.co 2020 rebirth and allow us to prepare the first stage of the permalink function to work!
The experiment with the archive code was updated to reflect this new information and finishes the "Review Image Order" task we create at the meeting, the first step to close this issue.

**Comment by tiagobugarin** [comment] 2020-05-05 04:19
Following the meeting from this afternoon (may 4th, 2020) we defined some steps to resolve this issue.

Second, is to merge the archive code into the Master branch, to have it pulled into `alpha` site and tested. All went well and alpha is ready to be reviewed for production.

**Comment by tiagobugarin** [comment] 2020-05-05 04:23
Ohhhh remember something, validators and browser compatibility!

Went down the path to validate de code and verify compatibility as #60 mandates. Code is ok and ready to be reviewed for production.

And now I think this third step gets us to finally have this issue ready to be closed.

**Comment by bruquevedo** [comment] 2020-05-05 13:13
> 
> 
> Following the meeting from this afternoon (may 4th, 2020) we defined some steps to resolve this issue.
> 
> Second, is to merge the archive code into the Master branch, to have it pulled into `alpha` site and tested. All went well and alpha is ready to be reviewed for production.

@tiagobugarin I just tested the archive in alpha. 
- The image sequence is correct and the permalinks are working;
- I checked all the menu in each photo and everthing is working well;

Let's go to production :)

**Closed** 2020-05-05 13:18 UTC
Labels: bug, email, website
