### ISSUE TITLE
As a user, I want to know that I can see a new photo so that I can have a unique experience on the website

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#62] opened 2020-04-23 16:49 UTC
_0.0.4 Deadline: Wed 9:00_

_0.0.5 Deadline: Mon 9:00_

The great moment! Tell the users that we have a new image.

We need to send the final email to the users.

**Comment by bruquevedo** [comment] 2020-04-23 17:25
Hey @vjpixel @JoshuSantos and @tiagobugarin I analyzed the data from the responses we had in the last email question "What day and time do you prefer to receive our weekly emails?" and most testers prefer to receive the email during the week in the morning, between 8am and 10am. Based on this data, I suggest rethinking the day of sending this week's email

**Comment by vjpixel** [comment] 2020-04-23 19:33
How about we send the next one on Monday, at 8 am, and them move (back?) to send every Friday at 9 am?

**Comment by bruquevedo** [comment] 2020-04-23 19:36
@vjpixel I agree

**Comment by JoshuSantos** [comment] 2020-04-23 21:05
@vjpixel Ay, ay.

**Comment by tiagobugarin** [comment] 2020-04-24 09:34
> How about we send the next one on Monday, at 8 am, and them move (back?) to send every Friday at 9 am?

I may sound crazy and all but... here me out.
As a test to gather data, what if we send every week, starting from the next, on a different day at 8am?
Doing this we would have data points on different days of the week and would really understand how our testers get around their opening and clicking habits.

This would be a 5 week stretch, going from monday to friday and then, with enough data, we will have the general idea of what's better day to send bucoli.co's email.

**Comment by vjpixel** [comment] 2020-04-24 19:00
I think that this makes sense, but the first step is to know how to do this test in a scientific way. To make it sounds like a Sequential A/B Testing, but I'm not sure.

Studying how to do it and make a proposal, @tiagobugarin ?

**Comment by tiagobugarin** [comment] 2020-04-25 13:20
Since we just have a couple dozen testers i dont think an A/B testing would work, thus a suggested doing it with the whole lot every week, so all the data we can get is as close to meaningful as possible.
Keeping it as objective as possible we can compare the data from different days and have an idea of what to expect about opening and clicking.

**Comment by vjpixel** [comment] 2020-04-25 16:01
From what you said above, I understand that now we don't have enough users to do the test you're proposing right now. So our first question is: how much data is enough to have a meaningful answer to a sequential test? There a lot of other questions we need to answer to make a meaningful test.

I think we can study so we can know how many people we need to have meaningful data. Can you send me a link that describes the methodology you're proposing to apply, so I can learn and we can design it together.

**Comment by vjpixel** [comment] 2020-04-25 16:35
Since this discussion is not related to the issue, I created #71 no we can discuss there.

**Comment by bruquevedo** [comment] 2020-04-28 21:26
the e-mail was sent. @tiagobugarin could you please review this issue?

**Comment by tiagobugarin** [comment] 2020-04-28 23:14
i can confirm!

**Comment by vjpixel** [comment] 2020-05-05 21:45
Since we decided to create the image for the next week in this Sprint, I put the deadlines for both products in the description.

**Comment by bruquevedo** [comment] 2020-05-06 13:15
email from the sprint 0.0.5 sent to our community

**Comment by bruquevedo** [comment] 2020-05-06 13:18
@tiagobugarin could you please review this issue and change the milestone to 0.0.5?

**Comment by tiagobugarin** [comment] 2020-05-08 20:11
i confirm the email...

closing, bumping to 0.0.5 and moving to next backlog

**Comment by bruquevedo** [comment] 2020-05-12 11:40
Email sent to our community. @tiagobugarin could you please review?

**Comment by tiagobugarin** [comment] 2020-05-13 02:59
Waited a few ours to see the results of the campaing and review here.

There was 28 successfully sent emaisl (100%).

I can confirm! Closing and moving.

**Closed** 2020-05-13 02:59 UTC
Labels: email, enhancement, recurring
